### ISSUE TITLE
NameError: uninitialized constant ActiveSupport::Callbacks

### ISSUE THREAD

**Issue by ryanking** [NZKoz/cassandra_object#1]
I'm trying to get the latest version integrated into our app (plus another changeset on my branch) and I'm getting this:

> > CassandraStatus
> > NameError: uninitialized constant ActiveSupport::Callbacks
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:263:in `load_missing_constant'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:453:in`const_missing_not_from_s3_library'
> >     from /Users/ryan/code/twitter/vendor/gems/aws-s3-0.6.2/lib/aws/s3/extensions.rb:206:in `const_missing'
> >     from /Users/ryan/code/twitter/vendor/gems/cassandra_object/lib/cassandra_object/legacy_callbacks.rb:4
> >     from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
> >     from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:496:in`require'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:342:in `new_constants_in'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:496:in`require'
> >     from /Users/ryan/code/twitter/vendor/gems/cassandra_object/lib/cassandra_object/base.rb:8
> >     from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
> >     from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:496:in `require'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:342:in`new_constants_in'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:496:in `require'
> >     from /Users/ryan/code/twitter/vendor/gems/cassandra_object/lib/cassandra_object.rb:28
> >     from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
> >     from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:496:in`require'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:342:in `new_constants_in'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:496:in`require'
> >     from /Users/ryan/code/twitter/app/models/cassandra_status.rb:1
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:203:in `load_without_new_constant_marking'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:203:in`load_file'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:342:in `new_constants_in'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:202:in`load_file'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:94:in `require_or_load'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:248:in`load_missing_constant'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:453:in `const_missing_not_from_s3_library'
> >     from /Users/ryan/code/twitter/vendor/gems/aws-s3-0.6.2/lib/aws/s3/extensions.rb:206:in`const_missing'
> >     from /Users/ryan/code/twitter/vendor/rails/activerecord/lib/../../activesupport/lib/active_support/dependencies.rb:465:in `const_missing'
> >     from (irb):2>>

**Comment by NZKoz** [comment]
OK, this is because the backporting I did didn't include AS::Callbacks which was introduced between 2.0 and 2.1 (@8664 in SVN rails/rails@aae37bb4f7edd6a1820e420a60560369c6064f33 in git)

Odds are you can simply add the following file to your own app (it's mostly stand alone)

http://github.com/rails/rails/blob/v2.3.5/activesupport/lib/active_support/callbacks.rb

**Comment by NZKoz** [comment]
My preference is not to extend the backporting too far back beyond what's needed for 2.3, so long as it's _possible_ for you guys to get the additional stuff backported yourselves

**Comment by ryanking** [comment]
I think i've got most of this sorted now.
