### ISSUE TITLE
Filters issue

### ISSUE THREAD

**Issue by romanoff** [NZKoz/cassandra_object#11]
If I am planning to use Cassandra, but in my application I have different kinds of filters - by status, by project, by user and so on. As I know - cassandra_object (as well as Cassandra itself) has no support of `:conditions` statement. The only way to avoid this problem is to write indexes of all this information just as you put some new values. Can anybody suggest some best practices about storing such information?

**Comment by NZKoz** [comment]
This is more a cassandra specific question.  I'd suggest you ask on the cassandra-user mailing list or the #cassandra irc channel

**Comment by romanoff** [comment]
Thanks. Will do that
