### ISSUE TITLE
PATCH: Cassandra gem 0.7.6+ doesn't support Cassandra::UUID

### ISSUE THREAD

**Issue by juscombr** [NZKoz/cassandra_object#13]
uninitialized constant Cassandra::UUID error, on Cassandra Gem >= 0.7.6.

This patch use SimpleUUID::UUID instead of Cassandra::UUID:

http://github.com/jusnavigandi/cassandra_object/commit/d6e898ce243de8ff5bb52871089d6efc70651342

**Comment by NZKoz** [comment]
Thanks, fixed in 64df85ec7e0d44a2b0cba832f33e4c9fc40a2635
