### ISSUE TITLE
The all and first method doesn't works with the newest cassandra.

### ISSUE THREAD

**Issue by cncolder** [NZKoz/cassandra_object#2]
Because there is not get_key_range method at there.

**Comment by tomafro** [comment]
The method get_key_range seems to have changed to get_range, with the syntax changing slightly too.  A simple patch for this is available here:

http://github.com/tomafro/cassandra_object/commit/9f9128b3eee6ae50418f5b92d70268cefb0472b8

**Comment by tomafro** [comment]
This patch has been applied, and they seem to work for me now.

**Comment by NZKoz** [comment]
closing
