### ISSUE TITLE
PATCH: after_create callback is never called

### ISSUE THREAD

**Issue by tomafro** [NZKoz/cassandra_object#3]
after_create is never being called because the run_callbacks :create .... block always returns false.  Patch and crappy test:

http://github.com/tomafro/cassandra_object/commit/467acc99d95b7b37247b39f527dd4bba611e7812

**Comment by NZKoz** [comment]
merged.

Thanks for the bundler incantations also ;)

**Comment by NZKoz** [comment]
a
