### ISSUE TITLE
[PATCH] Non-unique assocation should not require a :reversed option

### ISSUE THREAD

**Issue by tomafro** [NZKoz/cassandra_object#4]
Given the following association:

```
class Zoo < CassandraObject
  association :animals, :unique=>false
end
```

Reading this association would fail, with an error from the cassandra gem stating 'Required field reversed is unset!'.  This is because the reversed option is passed as nil, not false.

Patch: http://github.com/tomafro/cassandra_object/commit/b2b504469c7720eced76aeb24d353a94cc83353c

**Comment by NZKoz** [comment]
Merged, thanks!
