### ISSUE TITLE
Error using latest git snapshot of Rails 3

### ISSUE THREAD

**Issue by Tuxie** [NZKoz/cassandra_object#6]
With Gemfile:
    gem "rails", '3.0.0.beta'
    gem "cassandra_object", :git => "git://github.com/NZKoz/cassandra_object.git"
This works:
    IRB> User.new(:nick => 'Tuxie')
    #<User:0x4b271f0 @changed_attributes={"nick"=>nil}, @key=nil, @new_record=true, @attributes={"nick"=>"Tuxie"}, @schema_version=0>

But with Gemfile:
    gem "rails", :git => "git://github.com/rails/rails.git"
    gem "cassandra_object", :git => "git://github.com/NZKoz/cassandra_object.git"
This happens:
    IRB> User.new(:nick => 'Tuxie')
    NoMethodError: You have a nil object when you didn't expect it!
    You might have expected an instance of Array.
    The error occurred while evaluating nil.include?
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/rails-16a5e918a06649ffac24fd5873b875daf66212ad-master/activemodel/lib/active_model/dirty.rb:125:in `attribute_changed?'
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/cassandra_object-13c3c2c8949e63e16c17dc38b03522e12e5a8476-master/lib/cassandra_object/dirty.rb:19:in`write_attribute'
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/cassandra_object-13c3c2c8949e63e16c17dc38b03522e12e5a8476-master/lib/cassandra_object/attributes.rb:89:in `attribute='
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/rails-16a5e918a06649ffac24fd5873b875daf66212ad-master/activemodel/lib/active_model/attribute_methods.rb:262:in`send'
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/rails-16a5e918a06649ffac24fd5873b875daf66212ad-master/activemodel/lib/active_model/attribute_methods.rb:262:in `nick='
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/cassandra_object-13c3c2c8949e63e16c17dc38b03522e12e5a8476-master/lib/cassandra_object/attributes.rb:74:in`send'
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/cassandra_object-13c3c2c8949e63e16c17dc38b03522e12e5a8476-master/lib/cassandra_object/attributes.rb:74:in `attributes='
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/cassandra_object-13c3c2c8949e63e16c17dc38b03522e12e5a8476-master/lib/cassandra_object/attributes.rb:73:in`each'
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/cassandra_object-13c3c2c8949e63e16c17dc38b03522e12e5a8476-master/lib/cassandra_object/attributes.rb:73:in `attributes='
        from /home/tuxie/.bundle/ruby/1.8/bundler/gems/cassandra_object-13c3c2c8949e63e16c17dc38b03522e12e5a8476-master/lib/cassandra_object/base.rb:98:in`initialize'
        from (irb):1:in `new'
        from (irb):1

**Comment by fannar** [comment]
Having same problem with gem "rails", '3.0.0.beta2'

**Comment by tritonrc** [comment]
The Rails devs introduced a change in beta2 that was reverted in beta3.

**Comment by NZKoz** [comment]
This works with 3.0.0.beta3 and later
