### ISSUE TITLE
[PATCH]  Correcting get_range in "all" querying

### ISSUE THREAD

**Issue by gideondk** [NZKoz/cassandra_object#7]
Running the newest Cassandra Beta (0.6 Beta 3) in combination with the HEAD of the Cassandra Ruby Library, querying for "all" objects returns "nil" objects.

Currently, the get_range() function returns on ore more columns wrapped into "CassandraThrift::KeySlice" objects. The current implementation expects the columns keys as return values. 

The added patch fixes this problem by "getting" the key from the retrieved object. For compatibility with older versions, maybe check the version of the libraries and act appropriately (as type checking is too costly)? 

http://gist.github.com/340381

**Comment by NZKoz** [comment]
Fixed in 2a5207eaaa07181627c38eb53d9b67dfd8467052
