### ISSUE TITLE
Cassandra 0.6 + Cassandra object

### ISSUE THREAD

**Issue by romanoff** [NZKoz/cassandra_object#8]
Have found that cassandra_object is compatible with cassandra 0.7.6 gem. I have used cassandra_object and cassandra 0.7.6 gem, rails3 beta 3, ruby 1.9.1. At the moment I just get 
    NameError: uninitialized constant CassandraObject::Base error 
although this gems are written in Gemfile. 
(`CassandraObject` class is visible, but `CassandraObject::Base` is not)

**Comment by NZKoz** [comment]
Please try with the current master and re-open if you're still having issues.
